name: Publish
permissions: {}
concurrency:
  group: publish-${{ github.event.push.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: self-hosted
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
      with:
        enable-cache: false
        prune-cache: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version-file: pyproject.toml
    - run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
    - run: uv build
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      id: upload-artifact
      with:
        name: dist
        path: dist/
        if-no-files-found: error
  create-release:
    needs:
    - build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        artifact-ids: ${{ needs.build.outputs.artifact-id }}
        path: dist/
    - name: create release
      run: gh release create --draft --repo ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME}
        dist/*
      env:
        GH_TOKEN: ${{ github.token }}
  publish-pypi:
    needs:
    - build
    environment:
      name: publish
      url: https://pypi.org/project/Flask/${{ github.ref_name }}
    runs-on: self-hosted
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        artifact-ids: ${{ needs.build.outputs.artifact-id }}
        path: dist/
    - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
      with:
        packages-dir: dist/
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  push:
    tags:
    - '*'
